server:
  port: 8088

spring:
  application:
    name: greenpark
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.162.177/greenpark?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: weibingrui1808.
  redis:
    host: localhost
    port: 6379
    password:
    connect-timeout: 10000

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

